import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:nouri/core/notifications/notification_channels_ids.dart';
import 'package:nouri/core/notifications/notification_route.dart';
import 'package:nouri/core/notifications/task_alert.dart';

/// The user's requirement, in their own words:
///
///   «i don't need to open the app to know what i have to do, i need alarms
///    for each task ... from alarms i know what this task»
///
/// Which reduces to one testable property: **no two alerts may sound alike.**
/// Android ties sound to channel, so that means no two may share a channel or
/// a sound resource either.
void main() {
  group('the sounds', () {
    test('every alert names a sound file that exists', () {
      // Generated by tool/make_alert_sounds.py and committed. A missing one
      // fails the Gradle build with a message that does not mention the file,
      // so it is worth catching here instead.
      for (final kind in TaskAlertKind.values) {
        final f = File('android/app/src/main/res/raw/${kind.sound}.wav');
        expect(f.existsSync(), isTrue, reason: '${kind.name} -> ${kind.sound}');
      }
    });

    test('no two alerts share a sound', () {
      final sounds = TaskAlertKind.values.map((k) => k.sound).toList();
      expect(sounds.toSet().length, sounds.length,
          reason: 'the whole point is telling them apart by ear');
    });

    test('no two alerts share a channel', () {
      // Sharing a channel would merge their sounds however different the
      // files are, because Android reads the sound off the channel.
      final ids = TaskAlertKind.values.map((k) => k.channelId).toList();
      expect(ids.toSet().length, ids.length);
    });

    test('every sound is small enough to ship nineteen of', () {
      for (final kind in TaskAlertKind.values) {
        final f = File('android/app/src/main/res/raw/${kind.sound}.wav');
        expect(f.lengthSync(), lessThan(120 * 1024), reason: kind.sound);
      }
    });

    test('the nineteen together cost less than one stock recitation', () {
      final total = TaskAlertKind.values.fold<int>(
        0,
        (a, k) =>
            a + File('android/app/src/main/res/raw/${k.sound}.wav').lengthSync(),
      );
      // The bound this guard has always really been about: synthesising the
      // tones must stay cheaper than recording them. It still is, by a wide
      // margin — 1.11 MB for all nineteen against 6.98 MB for the five
      // recitations, i.e. less than a single average adhan file.
      //
      // Raised from 1 MB on 9 September 2026, when the tones stopped being
      // sums of sine waves and became filtered noise and struck bells.
      // Running water and a bell left to ring cannot be had in a fifth of a
      // second; the extra 380 KB is that, and nothing else.
      expect(total, lessThan(1536 * 1024),
          reason: 'one stock recording would have cost more than all of these');
    });

    test('resource names are legal Android raw identifiers', () {
      // res/raw names must be lowercase a-z, 0-9 and underscore, and must not
      // start with a digit.
      final legal = RegExp(r'^[a-z][a-z0-9_]*$');
      for (final kind in TaskAlertKind.values) {
        expect(legal.hasMatch(kind.sound), isTrue, reason: kind.sound);
      }
    });
  });

  group('the mapping from planned tasks', () {
    test('every task id the planner emits maps to an alert', () {
      // A task the planner places but that maps to nothing would arrive
      // silent, which is the one outcome this slice exists to prevent.
      const ids = [
        'morning-athkar',
        'evening-athkar',
        'tasbeeh',
        'quran-wird',
        'sleep-athkar',
        'first-meal',
        'last-meal',
        'walk',
        'knowledge-read',
        'knowledge-listen',
        'knowledge-skill',
        'calls',
        'phone-time',
      ];
      for (final id in ids) {
        expect(alertKindForTaskId(id), isNotNull, reason: id);
      }
    });

    test('the three knowledge faces share one sound — they are one block', () {
      // Rule 5 of the planner: reading, listening and skill rotate as one
      // flexible block, so they should not sound like three different things.
      expect(alertKindForTaskId('knowledge-read'),
          alertKindForTaskId('knowledge-skill'));
      expect(alertKindForTaskId('knowledge-listen'),
          alertKindForTaskId('knowledge-read'));
    });

    test('both meals sound the same — it is the same kind of thing', () {
      expect(alertKindForTaskId('first-meal'), alertKindForTaskId('last-meal'));
    });

    test('every alarmable id has both a sound and a number', () {
      // The two halves have to agree. An id with a kind but no place in
      // alarmableTaskIds gets no notification id and is silently skipped;
      // one with a number but no kind has nothing to sound.
      for (final id in alarmableTaskIds) {
        expect(alertKindForTaskId(id), isNotNull,
            reason: '$id is numbered but has no sound');
      }
    });

    test('the numbering order is append-only', () {
      // taskAlarmId uses the index, so inserting into the middle renumbers
      // alarms already sitting in AlarmManager on the user's phone. This
      // pins the prefix; adding to the end is fine.
      expect(alarmableTaskIds.take(5), [
        'morning-athkar',
        'evening-athkar',
        'sleep-athkar',
        'tasbeeh',
        'quran-wird',
      ]);
    });

    test('no id appears twice in the numbering', () {
      expect(alarmableTaskIds.toSet().length, alarmableTaskIds.length);
    });

    test('an unknown id is null rather than a throw', () {
      // An alarm scheduled by an older version can still be in AlarmManager.
      expect(alertKindForTaskId('nonsense-from-2025'), isNull);
    });
  });

  group('the copy', () {
    test('every kind has real copy', () {
      for (final k in TaskAlertKind.values) {
        expect(k.title.trim(), isNotEmpty, reason: k.name);
        expect(k.body.trim(), isNotEmpty, reason: k.name);
      }
    });

    test('nothing accuses', () {
      for (final k in TaskAlertKind.values) {
        final text = '${k.title} ${k.body} ${k.followUpQuestion ?? ''}';
        for (final w in ['فاتتك', 'ضيعت', 'فشل', 'كسلان', 'مقصر']) {
          expect(text.contains(w), isFalse, reason: '${k.name}: $w');
        }
      }
    });

    test('every follow-up is phrased as a question', () {
      for (final k in TaskAlertKind.values) {
        if (k.followUpQuestion == null) continue;
        expect(k.followUpQuestion, contains('؟'), reason: k.name);
      }
    });

    test('a kind that asks names both when and what', () {
      for (final k in TaskAlertKind.values) {
        expect(k.followUpAfter == null, k.followUpQuestion == null,
            reason: '${k.name} has one half of a follow-up and not the other');
      }
    });
  });

  group('what the user asked for by name', () {
    test('the meal asks half an hour later', () {
      // «after 30 mins ask me are you ate?»
      expect(TaskAlertKind.meal.followUpAfter, const Duration(minutes: 30));
      expect(TaskAlertKind.meal.followUpQuestion, contains('كلت'));
    });

    test('every kind names its own resource', () {
      // Naming only. Whether the file actually *sounds* like the task is a
      // claim about waveforms, and asserting it here — as this test once did,
      // under the name «water sounds like water» — proved nothing: it would
      // have passed with all nineteen files holding the same recording.
      // `alert_sound_character_test` measures the audio instead.
      expect(TaskAlertKind.water.sound, 'alert_water');
      expect(TaskAlertKind.walk.sound, 'alert_walk');
    });

    test('the morning and evening athkar do not sound alike', () {
      expect(TaskAlertKind.athkarMorning.sound,
          isNot(TaskAlertKind.athkarEvening.sound));
    });

    test('phone time is not asked about', () {
      // It already reports itself on its card, and «قعدت على الموبايل؟» would
      // be Nouri policing something it has no business policing.
      expect(TaskAlertKind.phone.followUpAfter, isNull);
    });
  });

  group('routing', () {
    test('every payload parses to a route', () {
      for (final k in TaskAlertKind.values) {
        expect(NotificationRoute.parse(k.payload), isNotNull, reason: k.name);
      }
    });

    test('no task alert lands on the adhan channel', () {
      // The adhan is the loudest thing Nouri owns. Nothing else borrows it.
      for (final k in TaskAlertKind.values) {
        expect(k.channelId, isNot(channelAdhan), reason: k.name);
      }
    });
  });
}
