// Generates docs/athkar-verification.md — a plain sheet listing every dhikr
// with its text, count, source and virtue, so a human can check it against a
// printed حصن المسلم before the app is relied on.
//
// Run: dart run tool/generate_athkar_verification.dart
//
// ignore_for_file: avoid_print — this is a command-line tool.

import 'dart:convert';
import 'dart:io';

import 'package:nouri/data/athkar/athkar_item.dart';

const _categoryTitles = {
  'morning': 'أذكار الصباح',
  'evening': 'أذكار المساء',
  'sleep': 'أذكار النوم',
  'tasbeeh': 'التسبيح',
};

const _arabicDigits = '٠١٢٣٤٥٦٧٨٩';

String ar(int n) =>
    n.toString().split('').map((d) => _arabicDigits[int.parse(d)]).join();

void main() {
  final buffer = StringBuffer()
    ..writeln('# ورقة مراجعة الأذكار — Athkar verification sheet')
    ..writeln()
    ..writeln('> **This file has NOT yet been checked against a printed copy.**')
    ..writeln('> Nouri must not be treated as an authority on these texts until')
    ..writeln('> someone has verified every entry below against a physical')
    ..writeln('> حصن المسلم or an equivalent trusted source.')
    ..writeln()
    ..writeln('Generated by `tool/generate_athkar_verification.dart` from the')
    ..writeln('JSON assets in `assets/athkar/`. Regenerate after any edit.')
    ..writeln()
    ..writeln('## How to review')
    ..writeln()
    ..writeln('For each entry, check three things:')
    ..writeln()
    ..writeln('1. **النص** — wording and tashkeel match the printed source.')
    ..writeln('2. **العدد** — the repeat count matches the narration.')
    ..writeln('3. **الفضل** — where a virtue is stated, it is accurate and not')
    ..writeln('   overstated. Where it says «غير مذكور», nothing is claimed —')
    ..writeln('   that is deliberate, not an omission to be filled in casually.')
    ..writeln()
    ..writeln('Anything doubtful should have its `virtue` set back to `null` in')
    ..writeln('the JSON rather than reworded.')
    ..writeln();

  var totalItems = 0;
  var withVirtue = 0;

  for (final category in _categoryTitles.keys) {
    final file = File('assets/athkar/$category.json');
    if (!file.existsSync()) {
      print('missing: ${file.path}');
      continue;
    }

    final set = AthkarSet.fromJson(
        jsonDecode(file.readAsStringSync()) as Map<String, dynamic>);

    buffer
      ..writeln('---')
      ..writeln()
      ..writeln('## ${_categoryTitles[category]}')
      ..writeln()
      ..writeln(
          '`assets/athkar/$category.json` · النسخة ${ar(set.version)} · '
          '${ar(set.items.length)} ذكر · ${ar(set.totalRepeats)} تكرار')
      ..writeln();

    for (var i = 0; i < set.items.length; i++) {
      final item = set.items[i];
      totalItems++;
      if (item.hasVirtue) withVirtue++;

      buffer
        ..writeln('### ${ar(i + 1)}. `${item.id}`')
        ..writeln()
        ..writeln('> ${item.text}')
        ..writeln()
        ..writeln('- **العدد:** ${ar(item.count)}')
        ..writeln('- **المصدر:** ${item.source}')
        ..writeln(
            '- **الفضل:** ${item.hasVirtue ? item.virtue : '(غير مذكور)'}');
      if (item.note != null) {
        buffer.writeln('- **ملاحظة:** ${item.note}');
      }
      buffer.writeln();
    }
  }

  buffer
    ..writeln('---')
    ..writeln()
    ..writeln('## الإجمالي')
    ..writeln()
    ..writeln('- عدد الأذكار: ${ar(totalItems)}')
    ..writeln('- منها بفضل مذكور: ${ar(withVirtue)}')
    ..writeln('- بدون فضل مذكور: ${ar(totalItems - withVirtue)}')
    ..writeln()
    ..writeln('Every entry carries a source. A blank virtue means the wording')
    ..writeln('was not well-established enough to ship — by design.');

  final out = File('docs/athkar-verification.md');
  out.writeAsStringSync(buffer.toString());
  print('wrote ${out.path}');
  print('$totalItems athkar, $withVirtue with a stated virtue');
}
