/// One row per thing Nouri can call you about, and everything about it.
///
/// **Android ties a notification's sound to its channel, not to the
/// notification.** That single fact shapes this file: "a different sound for
/// every task" means "a channel for every task", so each kind below owns a
/// channel id, a raw sound resource, its copy, where tapping it goes, and
/// whether it asks afterwards.
///
/// Keeping all of that in one enum is the point. A new kind of alert is one
/// entry here rather than five edits spread across the scheduler, the channel
/// list, the route parser and the copy.
///
/// The user's reason for wanting this, in their own words: *"i don't need to
/// open the app to know what i have to do ... from alarms i know what this
/// task."* So no two kinds may share a sound, and a test enforces it.
library;

/// Every alert Nouri can raise, and its sound.
///
/// Sounds are generated by `tool/make_alert_sounds.py` and committed as WAV in
/// `android/app/src/main/res/raw`. Synthesised rather than downloaded: no
/// licence to honour, nothing that can be taken down, ~40 KB each, and any of
/// them can be retuned by editing one line of that script.
///
/// The **adhan is deliberately absent** — it is not a tone and is handled
/// separately, one channel per prayer, awaiting real recitations.
enum TaskAlertKind {
  water(
    sound: 'alert_water',
    channelId: 'alert_water_v1',
    title: 'مياه',
    body: 'اشرب شوية مياه',
    payload: 'water',
  ),

  walk(
    sound: 'alert_walk',
    channelId: 'alert_walk_v1',
    title: 'مشي',
    body: 'وقت المشي. يلا نتحرك شوية',
    payload: 'task:walk',
    followUpAfter: Duration(minutes: 45),
    followUpQuestion: 'مشيت؟',
  ),

  workout(
    sound: 'alert_workout',
    channelId: 'alert_workout_v1',
    title: 'تمارين البيت',
    body: 'وقت التمرين',
    payload: 'task:workout',
    followUpAfter: Duration(minutes: 45),
    followUpQuestion: 'تمرّنت؟',
  ),

  meal(
    sound: 'alert_meal',
    channelId: 'alert_meal_v1',
    title: 'وجبة',
    body: 'وقت الأكل. سجّل وجبتك بعدها',
    payload: 'task:first-meal',
    // The user's own example: "after 30 mins ask me are you ate?"
    followUpAfter: Duration(minutes: 30),
    followUpQuestion: 'كلت؟ سجّل الوجبة وإحساسك بعدها',
  ),

  tasbeeh(
    sound: 'alert_tasbeeh',
    channelId: 'alert_tasbeeh_v1',
    title: 'تسبيح',
    body: 'وقت التسبيح',
    payload: 'task:tasbeeh',
    followUpAfter: Duration(minutes: 30),
    followUpQuestion: 'سبّحت؟',
  ),

  wird(
    sound: 'alert_wird',
    channelId: 'alert_wird_v2',
    title: 'ورد القرآن',
    body: 'ورد النهاردة — ربع من مصحفك',
    payload: 'quran',
  ),

  athkarMorning(
    sound: 'alert_athkar_morning',
    channelId: 'alert_athkar_morning_v1',
    title: 'أذكار الصباح',
    body: 'وقت أذكار الصباح — خمس دقايق بس',
    payload: 'athkar:morning',
  ),

  athkarEvening(
    sound: 'alert_athkar_evening',
    channelId: 'alert_athkar_evening_v1',
    title: 'أذكار المساء',
    body: 'قرب المغرب — وقت أذكار المسا',
    payload: 'athkar:evening',
  ),

  athkarSleep(
    sound: 'alert_athkar_sleep',
    channelId: 'alert_athkar_sleep_v1',
    title: 'أذكار النوم',
    body: 'قبل ما تنام، خد أذكار النوم',
    payload: 'athkar:sleep',
  ),

  qiyam(
    sound: 'alert_qiyam',
    channelId: 'alert_qiyam_v1',
    title: 'قيام الليل',
    body: 'الثلث الأخير — لو قدرت',
    payload: 'qiyam',
  ),

  knowledge(
    sound: 'alert_knowledge',
    channelId: 'alert_knowledge_v1',
    title: 'وقت المعرفة',
    body: 'وقت القراءة أو التعلّم',
    payload: 'task:knowledge',
    followUpAfter: Duration(minutes: 45),
    followUpQuestion: 'قريت النهاردة؟',
  ),

  phone(
    sound: 'alert_phone',
    channelId: 'alert_phone_v1',
    title: 'وقت الموبايل',
    body: 'ده وقت الموبايل المحجوز',
    payload: 'task:phone-time',
    asAlarm: false,
  ),

  calls(
    sound: 'alert_calls',
    channelId: 'alert_calls_v1',
    title: 'مكالمات',
    body: 'وقت المكالمات — كلّم اللي في بالك',
    payload: 'task:calls',
  ),

  budget(
    sound: 'alert_budget',
    channelId: 'alert_budget_v1',
    title: 'الميزانية',
    body: 'نظرة سريعة على مصاريف الشهر',
    payload: 'finance',
    asAlarm: false,
  ),

  reminder(
    sound: 'alert_reminder',
    channelId: 'alert_reminder_v1',
    title: 'تذكير',
    body: 'عندك تذكير النهاردة',
    payload: 'reminder:0',
  ),

  fasting(
    sound: 'alert_fasting',
    channelId: 'alert_fasting_v1',
    title: 'صيام بكرة؟',
    body: 'بكرة من أيام الصيام المستحبة',
    payload: 'fasting',
    asAlarm: false,
  ),

  review(
    sound: 'alert_review',
    channelId: 'alert_review_v1',
    title: 'نوري',
    body: 'تحب نراجع يومك سوا؟',
    payload: 'review:daily',
    asAlarm: false,
  ),

  /// The gentle "did you?" that follows a task. Quietest of the eighteen: it
  /// is only asking, and it must not nag.
  followUp(
    sound: 'alert_followup',
    channelId: 'alert_followup_v1',
    title: 'نوري',
    body: 'سؤال سريع',
    payload: 'review:daily',
    asAlarm: false,
  ),

  iqama(
    sound: 'alert_iqama',
    channelId: 'alert_iqama_v2',
    title: 'الإقامة',
    body: 'قربت الإقامة',
    payload: 'prayer:dhuhr',
  );

  const TaskAlertKind({
    required this.sound,
    required this.channelId,
    required this.title,
    required this.body,
    required this.payload,
    this.asAlarm = true,
    this.followUpAfter,
    this.followUpQuestion,
  });

  /// What this tone is called in الأصوات, where the user auditions them.
  ///
  /// Almost always the notification's own title, which is what they will read
  /// when it arrives. The two exceptions are the ones titled «نوري» — a name,
  /// not a subject — which would otherwise appear twice in the list with no
  /// way to tell which was which.
  String get soundName => switch (this) {
        TaskAlertKind.followUp => 'سؤال المتابعة',
        TaskAlertKind.review => 'مراجعة اليوم',
        _ => title,
      };

  /// Whether this plays at **alarm** volume rather than notification volume.
  ///
  /// The user asked for alarms — «i need alarms for each task» — and a nudge
  /// at notification volume on a phone in a pocket is not one. So anything
  /// that summons the user to *do* something uses alarm usage.
  ///
  /// The exceptions are the ones that only inform: the budget note, the phone
  /// cap, the fasting offer, the end-of-day review and the soft «عملتها؟».
  /// Waking someone at alarm volume to tell them they are near a budget would
  /// be the kind of app that gets uninstalled.
  final bool asAlarm;

  /// The `res/raw` resource name, without extension.
  final String sound;

  /// Its own channel — this is what makes the sound its own.
  final String channelId;

  final String title;
  final String body;

  /// Where tapping it goes. Parsed by [NotificationRoute].
  final String payload;

  /// How long after the alert to ask whether it happened, or null for the
  /// kinds that should not be asked about.
  ///
  /// Not everything wants a question. وقت الموبايل already reports itself on
  /// its card, and asking «قعدت على الموبايل؟» would be Nouri nagging about
  /// something it has no business policing.
  final Duration? followUpAfter;

  final String? followUpQuestion;
}

/// Every task id that can carry an alarm, in a **fixed, append-only order**.
///
/// The order is load-bearing: `taskAlarmId` uses the index, so inserting into
/// the middle would renumber alarms already sitting in AlarmManager. Append
/// only, exactly like [NotificationSlot].
///
/// It is keyed on the *task* rather than the alert kind because several tasks
/// share a kind — both meals, and all three faces of knowledge time. Keying
/// the id on the kind gave أول وجبة and آخر وجبة the same id, so the later one
/// silently overwrote the earlier and the first meal of the day was never
/// announced. Found by a test asserting ids are unique.
const alarmableTaskIds = <String>[
  'morning-athkar',
  'evening-athkar',
  'sleep-athkar',
  'tasbeeh',
  'quran-wird',
  'first-meal',
  'last-meal',
  'walk',
  'workout',
  'knowledge-read',
  'knowledge-listen',
  'knowledge-skill',
  'calls',
  'phone-time',
];

/// The alert a planned task should sound with, or null when it has none.
///
/// The ids are the ones `dailyTasksFor` emits. A task the planner places but
/// that maps to nothing here would arrive silent, which is the one outcome
/// this whole slice exists to prevent — so a test walks every id.
TaskAlertKind? alertKindForTaskId(String taskId) => switch (taskId) {
      'morning-athkar' => TaskAlertKind.athkarMorning,
      'evening-athkar' => TaskAlertKind.athkarEvening,
      'sleep-athkar' => TaskAlertKind.athkarSleep,
      'tasbeeh' => TaskAlertKind.tasbeeh,
      'quran-wird' => TaskAlertKind.wird,
      'first-meal' || 'last-meal' => TaskAlertKind.meal,
      'walk' => TaskAlertKind.walk,
      // The planner does not place a workout yet — البدن → تمارين البيت is
      // opened by hand. The kind exists so that when it does, it already has
      // a sound of its own rather than borrowing the walk's.
      'workout' => TaskAlertKind.workout,
      'knowledge-read' ||
      'knowledge-listen' ||
      'knowledge-skill' =>
        TaskAlertKind.knowledge,
      'calls' => TaskAlertKind.calls,
      'phone-time' => TaskAlertKind.phone,
      _ => null,
    };
