import 'dart:convert';

/// A plan that came back from Claude, after it has been made safe.
///
/// **Everything here is parsed defensively and nothing here throws.** The input
/// is text generated by a language model: it can arrive wrapped in ``` fences,
/// with a sentence of preamble, with a field missing, with a string where a
/// number was asked for, or truncated halfway through because `max_tokens` ran
/// out. None of that is exceptional and none of it may reach the UI as an
/// exception — the day still has to be drawn.
///
/// The rule throughout is **drop, never invent**. A task whose id Nouri does
/// not recognise is discarded rather than guessed at, because a task with no
/// alert never rings, and a silent row in المهام looks like a promise Nouri
/// made and did not keep. A day that fails to parse falls back to `planDay`,
/// which is the floor this whole feature sits on.
class PlanDocument {
  const PlanDocument({
    required this.days,
    required this.books,
    required this.note,
  });

  final List<PlannedDay> days;

  /// Book recommendations, from the interests in the profile.
  ///
  /// The one part of §5.3 nothing else in the app could produce. Labelled as
  /// recommendations wherever they are shown: Nouri still claims nothing it
  /// has not been told.
  final List<BookSuggestion> books;

  /// Nouri's line about the plan. Two sentences at most, by the prompt.
  final String? note;

  bool get isEmpty => days.isEmpty && books.isEmpty;

  /// Parses a model reply, keeping whatever is well-formed.
  ///
  /// [allowedTaskIds] is not advisory. Anything outside it is dropped, however
  /// plausible it looks — the model was given the list and a task outside it
  /// cannot be rung.
  static PlanParseResult parse(
    String raw, {
    required Set<String> allowedTaskIds,
  }) {
    final cleaned = _stripFences(raw);
    if (cleaned.trim().isEmpty) {
      return const PlanParseResult.failed('رجعت خطة فاضية');
    }

    Object? decoded;
    try {
      decoded = jsonDecode(cleaned);
    } catch (_) {
      // One retry against the outermost {...} in the text. Models routinely
      // add a courteous sentence before the JSON despite being asked not to,
      // and throwing away an otherwise perfect plan over that would be a
      // failure the user pays for in a wasted API call.
      final salvaged = _outermostObject(cleaned);
      if (salvaged == null) {
        return const PlanParseResult.failed('مش قادر أقرا الخطة اللي رجعت');
      }
      try {
        decoded = jsonDecode(salvaged);
      } catch (_) {
        return const PlanParseResult.failed('مش قادر أقرا الخطة اللي رجعت');
      }
    }

    if (decoded is! Map) {
      return const PlanParseResult.failed('الخطة رجعت بشكل مش متوقع');
    }

    final days = <PlannedDay>[];
    final dropped = <String>[];

    for (final entry in _listOf(decoded['days'])) {
      if (entry is! Map) continue;
      final date = _dateOf(entry['date']);
      if (date == null) continue;

      final tasks = <PlannedEntry>[];
      for (final t in _listOf(entry['tasks'])) {
        if (t is! Map) continue;
        final id = _stringOf(t['id']);
        final at = _timeOf(t['at']);
        if (id == null || at == null) continue;

        if (!allowedTaskIds.contains(id)) {
          // Recorded rather than silently swallowed: if the model keeps
          // inventing the same id, that is a prompt to fix, and it is
          // invisible unless somebody counts.
          dropped.add(id);
          continue;
        }

        tasks.add(PlannedEntry(
          id: id,
          at: DateTime(date.year, date.month, date.day, at.$1, at.$2),
          minutes: _intOf(t['minutes']) ?? 30,
        ));
      }

      // A day whose tasks all fell away is not a day. Keeping it would blank
      // المهام for that date and look like a plan that said "do nothing".
      if (tasks.isEmpty) continue;

      tasks.sort((a, b) => a.at.compareTo(b.at));
      days.add(PlannedDay(date: date, tasks: tasks));
    }

    final books = <BookSuggestion>[];
    for (final b in _listOf(decoded['books'])) {
      if (b is! Map) continue;
      final title = _stringOf(b['title']);
      if (title == null) continue;
      books.add(BookSuggestion(title: title, why: _stringOf(b['why'])));
    }

    days.sort((a, b) => a.date.compareTo(b.date));

    return PlanParseResult(
      document: PlanDocument(
        days: days,
        books: books,
        note: _stringOf(decoded['note']),
      ),
      droppedTaskIds: dropped,
    );
  }

  /// Removes a ```json fence if the model added one.
  static String _stripFences(String raw) {
    var s = raw.trim();
    if (!s.startsWith('```')) return s;
    final firstBreak = s.indexOf('\n');
    if (firstBreak == -1) return s;
    s = s.substring(firstBreak + 1);
    final close = s.lastIndexOf('```');
    return close == -1 ? s.trim() : s.substring(0, close).trim();
  }

  /// The outermost `{...}` span, for a reply with prose either side of it.
  static String? _outermostObject(String s) {
    final start = s.indexOf('{');
    final end = s.lastIndexOf('}');
    if (start == -1 || end <= start) return null;
    return s.substring(start, end + 1);
  }

  static List<Object?> _listOf(Object? v) => v is List ? v : const [];

  static String? _stringOf(Object? v) {
    if (v is! String) return null;
    final t = v.trim();
    return t.isEmpty ? null : t;
  }

  static int? _intOf(Object? v) {
    if (v is int) return v;
    if (v is num) return v.toInt();
    // Models write "30" as often as 30, and rejecting the string would throw
    // away a whole task over a quotation mark.
    if (v is String) return int.tryParse(v.trim());
    return null;
  }

  static DateTime? _dateOf(Object? v) {
    final s = _stringOf(v);
    if (s == null) return null;
    final parts = s.split('-');
    if (parts.length != 3) return null;
    final y = int.tryParse(parts[0]);
    final m = int.tryParse(parts[1]);
    final d = int.tryParse(parts[2]);
    if (y == null || m == null || d == null) return null;
    if (m < 1 || m > 12 || d < 1 || d > 31) return null;
    // Constructed, never offset — and validated, because DateTime(2026, 13, 40)
    // is a real DateTime in Dart and would silently become February.
    final built = DateTime(y, m, d);
    if (built.month != m || built.day != d) return null;
    return built;
  }

  static (int, int)? _timeOf(Object? v) {
    final s = _stringOf(v);
    if (s == null) return null;
    final parts = s.split(':');
    if (parts.length < 2) return null;
    final h = int.tryParse(parts[0].trim());
    final m = int.tryParse(parts[1].trim());
    if (h == null || m == null) return null;
    if (h < 0 || h > 23 || m < 0 || m > 59) return null;
    return (h, m);
  }
}

class PlannedDay {
  const PlannedDay({required this.date, required this.tasks});
  final DateTime date;
  final List<PlannedEntry> tasks;
}

class PlannedEntry {
  const PlannedEntry({
    required this.id,
    required this.at,
    required this.minutes,
  });

  final String id;
  final DateTime at;
  final int minutes;
}

class BookSuggestion {
  const BookSuggestion({required this.title, this.why});
  final String title;
  final String? why;
}

/// The outcome of a parse: a document, or a reason the user can read.
class PlanParseResult {
  const PlanParseResult({
    required this.document,
    this.droppedTaskIds = const [],
  }) : failure = null;

  const PlanParseResult.failed(this.failure)
      : document = null,
        droppedTaskIds = const [];

  final PlanDocument? document;

  /// In Arabic, and in Nouri's voice: it is shown to the user as it is.
  final String? failure;

  /// Task ids the model invented. Never shown to the user — it is a note for
  /// whoever next reads the prompt.
  final List<String> droppedTaskIds;

  bool get ok => document != null;
}
